/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors:{
        "secondary-fixed":"#d0e6f2",
        "line":"#D6E1E7",
        "on-tertiary":"#ffffff",
        "on-secondary-fixed":"#091e27",
        "on-primary":"#ffffff",
        "surface-container-low":"#e8f6ff",
        "surface-container-high":"#d8ebf7",
        "on-error-container":"#93000a",
        "on-primary-fixed":"#001f23",
        "on-tertiary-container":"#ffefe6",
        "on-surface-variant":"#3e494a",
        "tertiary":"#814716",
        "on-primary-container":"#d5f9ff",
        "outline-variant":"#bdc8ca",
        "on-secondary":"#ffffff",
        "surface-container-lowest":"#ffffff",
        "frost":"#F2F6F8",
        "primary-container":"#0b7a86",
        "secondary-fixed-dim":"#b5cad6",
        "tertiary-container":"#9e5f2c",
        "on-primary-fixed-variant":"#004f57",
        "primary-fixed":"#99f0fe",
        "teal-tint":"#E2F1F3",
        "secondary-container":"#d0e6f2",
        "tertiary-fixed-dim":"#ffb782",
        "on-tertiary-fixed":"#301400",
        "on-secondary-fixed-variant":"#364954",
        "surface-variant":"#d2e5f2",
        "urgent-tint":"#FCE9E7",
        "surface-container":"#ddf1fd",
        "inverse-primary":"#7dd4e1",
        "error":"#ba1a1a",
        "on-error":"#ffffff",
        "success-tint":"#E4F3EA",
        "primary-fixed-dim":"#7dd4e1",
        "on-secondary-container":"#536772",
        "tertiary-fixed":"#ffdcc5",
        "surface-container-highest":"#d2e5f2",
        "attention-tint":"#FFF1DB",
        "on-background":"#0b1e26",
        "surface-bright":"#f4faff",
        "outline":"#6e797b",
        "secondary":"#4d616c",
        "success":"#2F8A5B",
        "attention":"#B96A00",
        "on-surface":"#0b1e26",
        "on-tertiary-fixed-variant":"#6e3906",
        "error-container":"#ffdad6",
        "urgent":"#D4372E",
        "background":"#f4faff",
        "surface-dim":"#cadde9",
        "inverse-surface":"#21333c",
        "inverse-on-surface":"#e1f3ff",
        "surface":"#FFFFFF",
        "surface-tint":"#006973",
        "primary":"#006069"
      },
      borderRadius:{
        "DEFAULT":"0.25rem",
        "lg":"0.5rem",
        "xl":"0.75rem",
        "full":"9999px"
      },
      spacing:{
        "space-lg":"1.5rem",
        "gutter":"1rem",
        "space-md":"1rem",
        "gutter-desktop":"1.5rem",
        "margin-desktop":"2rem",
        "space-xl":"2rem",
        "space-xs":"0.5rem",
        "margin":"1rem",
        "space-sm":"0.75rem"
      },
      fontFamily:{
        "stat-display":["Public Sans"],
        "label-md":["Public Sans"],
        "body-sm":["Public Sans"],
        "headline-md":["Public Sans"],
        "body-lg":["Public Sans"],
        "label-lg":["Public Sans"],
        "headline-sm":["Public Sans"],
        "title-md":["Public Sans"],
        "headline-lg":["Public Sans"]
      },
      fontSize:{
        "stat-display":["28px",{"lineHeight":"32px","fontWeight":"600"}],
        "label-md":["13px",{"lineHeight":"16px","fontWeight":"500"}],
        "body-sm":["13px",{"lineHeight":"18px","fontWeight":"400"}],
        "headline-md":["24px",{"lineHeight":"32px","fontWeight":"600"}],
        "body-lg":["15px",{"lineHeight":"22px","fontWeight":"400"}],
        "label-lg":["15px",{"lineHeight":"20px","fontWeight":"600"}],
        "headline-sm":["18px",{"lineHeight":"24px","fontWeight":"600"}],
        "title-md":["17px",{"lineHeight":"22px","fontWeight":"600"}],
        "headline-lg":["28px",{"lineHeight":"36px","fontWeight":"600"}]
      }
    }
  },
  plugins: [],
}
